sudo: required

env:
  - DOCKER_COMPOSE_VERSION=1.21.2

services:
  - docker

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - bash configs/webgrind.sh
  - ls -l

script:
  - docker version
  - docker-compose version
  - PACKAGE=/var/www docker-compose up -d
  - docker-compose ps
  - echo "Travis:" $TRAVIS_TEST_RESULT
  - docker exec -ti ysoffner-server-php7.2 php -i | grep Xdebug
  - if [[ $(docker exec -ti ysoffner-server-php7.2 php -i |grep xdebug.remote_enable |awk '{print $3}') == 'On ']];then
  echo 'Default is Off' && exit 0;
  fi


notifications:
  email:
    recipients:
      - ysoffner@gmail.com
    on_success: never # default: change
    on_failure: always # default: always