version: '3'
services:
  ysoffner-server-nginx:
    container_name: ysoffner-server-nginx
    image: nginx:latest
    ports:
      - 1000:80
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
      - ../webgrind/:/var/www/webgrind/
    networks:
      - ysoffner-server-net

  ysoffner-server-php:
    image: ysoffner/php:7.1.18-fpm-alpine
    container_name: ysoffner-server-php
    ports:
      - 9001:9000
    volumes:
      - ../configs/php.ini:/usr/local/etc/php/php.ini
      - ../webgrind/:/var/www/webgrind/
    networks:
      - ysoffner-server-net
  
  ysoffner-server-php5:
    image: ysoffner/php:5.6.30-fpm
    container_name: ysoffner-server-php5
    ports:
      - 9002:9000
    volumes:
      - ../configs/php.ini:/usr/local/etc/php/php.ini
      - ../webgrind/:/var/www/webgrind/
    networks:
      - ysoffner-server-net

networks:
  ysoffner-server-net:
    driver: bridge
