version: '3'

services:
  ysoffner-server-nginx:
    container_name: ysoffner-server-nginx
    image: nginx:latest
    networks:
      - webgrind
    ports:
      - 1000:80
      #- 1001:81
    volumes:
    # Path
    # - /file/path/to_analyse:/some/path/file
    
    # Configs
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
    
    # Repository of WebGrind
      - ./webgrind/:/var/www/webgrind/


  ysoffner-server-php7:
    container_name: ysoffner-server-php7
    image: ysoffner/php:7.1.18-fpm-alpine
    networks:
      - webgrind
    ports:
      - 9001:9000
    volumes:
    # - /file/path/to_analyse:/some/path/file
    
    # Configs
      - ./configs/php.ini:/usr/local/etc/php/php.ini
    
    # Repository of WebGrind
      - ./webgrind/:/var/www/webgrind/

  
  ysoffner-server-php5:
    container_name: ysoffner-server-php5
    image: ysoffner/php:5.6.30-fpm
    networks:
      - webgrind
    ports:
      - 9002:9000
    volumes:
    # - /file/path/to_analyse:/some/path/file
    
    # Configs
      - ./configs/php.ini:/usr/local/etc/php/php.ini
    
    # Repository of WebGrind
      - ./webgrind/:/var/www/webgrind/

networks:
  webgrind:
    driver: bridge